video_retrieval:
  published_after_days: 1 # Number of days back from now to look for videos

youtube_channel_ids:
  - UC-uhvujip5deVcEtLxnW8qg # TLDR News Golbal
  - UC-eegKVWEgBCa4OzjnK_PtA # TLDR News EU
  - UCz_3xlMTVUYYTQqCfh9lD7w # TLDR Daily

llm:
  provider: "groq"
  models:
    - "llama-3.3-70b-versatile"
    - "qwen-2.5-32b"
    - "llama-3.1-8b-instant"